apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    maistra.io/gateway-name: bookinfo-gateway
    maistra.io/gateway-namespace: bookinfo 
  labels:
    app: productpage
    service: productpage
  name: productpage
  namespace: istio-system
spec:
  host: productpage-bookinfo.apps.cluster-f8zbs.f8zbs.sandbox3071.opentlc.com
  port:
    targetPort: http2
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
